

export interface DriverRecord {
  id: string;
  name: string;
  licensePlate: string;
  contractStartDate: string; // ISO Date string YYYY-MM-DD (Source of truth)
  rentDuration?: string; // 租期 (Source from import)
  mode: 'kuaikuai' | 'kuaiwen';
  violationMode?: 'kuaikuai' | 'kuaiwen'; // NEW: 独立的违章查询模式
  totalPayable: number; // 应付
  actualPaid: number; // 实付
  overdueRentAmount: number; // API获取的往期逾期租金
  apiOverdueDetails?: any[]; // API返回的原始逾期账单列表 (For Export)
  
  // Current Violations (Affects Risk/Billing)
  violationCount: number; // 违章条数
  violationPoints: number; // 违章分数
  violationFine: number; // 违章罚款
  violationDeadline?: string; // 截至时间 (New)
  apiViolationDetails?: any[]; // NEW: API返回的原始违章列表

  // Historical Violations (Display Only, No Risk Impact)
  historyViolationCount: number; // 历史违章条数
  historyViolationPoints: number; // 历史违章分数
  historyViolationFine: number; // 历史违章罚款

  // Remind Status (New)
  lastRemindedDate?: string; // 最后一次点击“已催”按钮的日期 (YYYY-MM-DD)
}

export type RiskLevel = 'severe' | 'high' | 'due' | 'normal';

export interface RiskStatus {
  isArrears: boolean;
  arrearsAmount: number;
  expectedPaid: number;
  violationCost: number; // (points * 200) + fine
  totalDebt: number; // Arrears + Overdue + Violation Cost
  riskLevel: RiskLevel; // New multi-tier risk level
  isHighRisk: boolean; // Kept for backward compatibility (maps to high or severe)
  isDueDay: boolean; // 是否是交租日 (今日催缴)
  isPreDueDay: boolean; // 是否是交租日前一天 (明日催缴)
  isReminded: boolean; // 本轮是否已催
  riskReasons: string[];
  currentPeriod: number; // 1, 2, 3, or 4
  computedBillDate: string; // The calculated start date of the current cycle
  currentCycleArrears: number; // 仅本期欠款
  // Missing properties used in billing calculations and reminder templates
  unpaidRent: number;
  realTimeArrears: number;
  periodRange: string;
}

export type HighlightRule = 
  | 'smart_tiered'     // NEW: Purple(>1300) -> Red(>Weekly) -> Yellow(Due)
  | 'arrears_900'      // 欠租 >= 900
  | 'violation_600'    // 违章费 >= 600
  | 'overdue_0'        // 逾期 >= 0
  | 'total_1200'       // 总费用 >= 1200
  | 'rent_total_1000'; // 欠租+逾期 >= 1000

export type CardField = 'dates' | 'financials' | 'violations_active' | 'violations_history' | 'tags';

export interface ColorSettings {
  riskColor: string; // Used for Red/High
  dueColor: string;  // Used for Yellow/Due
  severeColor: string; // NEW: Used for Purple/Severe
  highlightRule: HighlightRule;
  cardFields: CardField[]; // NEW: Visible fields
}

// --- NEW: Memo Feature Types ---
export type MemoPriority = 'low' | 'medium' | 'high';

export interface Memo {
  id: string;
  text: string;
  isCompleted: boolean;
  priority: MemoPriority;
  category?: string; // NEW: 备忘录分类
  order?: number;    // NEW: 排序权重
  createdAt: string;
}

/**
 * Interface representing the structure of an architectural analysis report generated by Gemini.
 * Included to fix the missing export error in geminiService.ts.
 */
export interface ArchitectureReview {
  riskLevel: "Low" | "Medium" | "High";
  summary: string;
  changeFootprint: string;
  logicPreservation: string;
  expansionStrategy: string[];
  refactoredCode: string;
  dependencyMap: {
    source: string;
    target: string;
    relationship: string;
  }[];
}